In [1]:
import os

import numpy as np
import tensorflow as tf

os.environ["CUDA_VISIBLE_DEVICES"] = "3"
tf.__version__

'2.1.0'

In [7]:
inputs = np.random.random([32, 10, 8]).astype(np.float32)
print(f"inputs shape = {inputs.shape}")
print(f"inputs data =\n{inputs[0]}")
print()

simple_rnn = tf.keras.layers.SimpleRNN(4)

outputs = simple_rnn(inputs)  # The output has shape `[32, 4]`.

print(f"output shape = {outputs.shape}")
print(f"output data =\n{outputs[:4]}")
print()

inputs shape = (32, 10, 8)
inputs data =
[[0.11791843 0.36036023 0.08250206 0.980444   0.17340904 0.31438172
  0.8590786  0.1579886 ]
 [0.27903286 0.34724644 0.8908477  0.90245855 0.14376618 0.37838098
  0.42490956 0.9875257 ]
 [0.73622674 0.97920287 0.00960445 0.12180401 0.7325103  0.49344277
  0.8980612  0.76706755]
 [0.28771153 0.79352206 0.74421024 0.692867   0.26180696 0.52415335
  0.9122366  0.28689706]
 [0.82459223 0.2800132  0.88158417 0.04202219 0.35681722 0.29535744
  0.14877364 0.07261594]
 [0.9049979  0.83008003 0.08447954 0.13903004 0.98588294 0.34519053
  0.82959557 0.7579307 ]
 [0.58629394 0.05366091 0.11952674 0.60071623 0.3031389  0.99306905
  0.22525786 0.26165384]
 [0.9363037  0.24740547 0.23452705 0.6995885  0.20289932 0.83042216
  0.77043855 0.37940994]
 [0.9133311  0.31559023 0.75098616 0.3887628  0.31032196 0.65613467
  0.09954912 0.8378022 ]
 [0.7461201  0.26796272 0.9349275  0.04507281 0.16065137 0.9714873
  0.03111415 0.31637746]]

output shape = (32, 4)
outpu

In [11]:
simple_rnn = tf.keras.layers.SimpleRNN(4, return_sequences=True, return_state=True)

# whole_sequence_output has shape `[32, 10, 4]`.
# final_state has shape `[32, 4]`.
whole_sequence_output, final_state = simple_rnn(inputs)

print(f"whole_sequence_output shape = {whole_sequence_output.shape}")
print(f"whole_sequence_output data =\n{whole_sequence_output[0]}")
print()

whole_sequence_output shape = (32, 10, 4)
whole_sequence_output data =
[[ 0.13652837  0.20684393 -0.1390635  -0.29222235]
 [ 0.8769079  -0.06562431  0.19589455 -0.67914927]
 [ 0.87522763  0.78257376  0.20981136  0.5552057 ]
 [ 0.67880774 -0.52374023  0.82500196 -0.30344638]
 [ 0.940775    0.5362911   0.40211245 -0.39072365]
 [ 0.8997715   0.5778643   0.5282089  -0.00418649]
 [ 0.7574618  -0.44397476  0.7168948  -0.05206991]
 [ 0.8263472   0.7487867   0.36683664 -0.08395017]
 [ 0.9417173  -0.34482342  0.74092394 -0.59382373]
 [ 0.96752965  0.12554204  0.54544455  0.14318484]]



In [10]:
print(f"final_state shape = {final_state.shape}")
print(f"final_state data =\n{final_state}")
print()

final_state shape = (32, 4)
final_state data =
[[ 0.8621396  -0.21949466 -0.40293452  0.3053328 ]
 [ 0.8009163   0.47367385 -0.5189261   0.4030193 ]
 [ 0.5149594   0.68398595 -0.08926789  0.8781149 ]
 [ 0.77506584  0.1426603  -0.39114943  0.37567294]
 [ 0.91790164  0.81466043 -0.78081036  0.67783946]
 [ 0.8447895   0.70901567 -0.31777576  0.5601268 ]
 [ 0.9448732   0.5094439  -0.8352037   0.7345295 ]
 [ 0.5754674   0.7252196  -0.5401989   0.64536226]
 [ 0.9132816   0.1987134  -0.7306922   0.59841305]
 [ 0.8182018   0.4741538  -0.8362567  -0.09250544]
 [ 0.90859115 -0.15362337 -0.3152101   0.18850654]
 [ 0.8506242   0.6118408  -0.25945437  0.85446507]
 [ 0.8476969  -0.01364336  0.05416309  0.76598465]
 [ 0.9608614   0.3037074  -0.2757023   0.85225403]
 [ 0.48621112  0.89388114 -0.4472301   0.86731875]
 [ 0.71717     0.76611227 -0.09496133  0.7059291 ]
 [ 0.9472807  -0.0466105  -0.0975012   0.23525244]
 [ 0.91280174  0.48508647 -0.6404225   0.4404116 ]
 [ 0.48044872  0.7297311   0.038953