# 张量(Tensor)的结构操作

In [1]:
import os

import tensorflow as tf
import numpy as np

os.environ["CUDA_VISIBLE_DEVICES"] = "3"
tf.__version__

'2.1.0'

**张量结构操作** 如下：
- 张量创建；
- 索引切片；
- 维度变换；
- 合并分割；
- ...

### 创建张量

In [2]:
# 创建 常量
a = tf.constant([1, 2, 3], dtype=tf.float32)

# 创建 变量
x = tf.Variable(1.0, name="x", dtype=tf.float32)

tf.print(f"a shape = {a.shape}")
tf.print(f"a = {a}")
print()
tf.print(f"x shape = {x.shape}")
tf.print(f"x = {x}")
print()

a shape = (3,)
a = [1. 2. 3.]

x shape = ()
x = <tf.Variable 'x:0' shape=() dtype=float32, numpy=1.0>



In [3]:
# 创建 Vector(一维张量)

# 1.
vec_a = tf.range(1, 10, delta=2)

# 2.
vec_b = tf.linspace(0.0, 2 * 3.14, 10)

print(f"vec_a shape = {vec_a.shape}")
print(f"vec_a =\n{vec_a}")
print()
print(f"vec_b shape = {vec_b.shape}")
print(f"vec_b =\n{vec_b}")
print()

vec_a shape = (5,)
vec_a =
[1 3 5 7 9]

vec_b shape = (10,)
vec_b =
[0.        0.6977778 1.3955556 2.0933335 2.7911112 3.488889  4.186667
 4.8844447 5.5822225 6.28     ]



In [4]:
# 创建 Matrix(二维张量)

# 1.
m_ones = tf.ones([2, 2])

m_zeros = tf.zeros([3, 3])

m_zeros_1 = tf.zeros_like(m_ones, dtype=tf.float32)

m_zeros_2 = tf.fill((3, 2), 5)


print(f"【m_ones】 shape = {m_ones.shape}")
print(f"【m_ones】 =\n{m_ones}")
print()
print(f"【m_zeros】 shape = {m_zeros.shape}")
print(f"【m_zeros】 =\n{m_zeros}")
print()
print(f"【m_zeros_1】 shape = {m_zeros_1.shape}")
print(f"【m_zeros_1】 =\n{m_zeros_1}")
print()
print(f"【m_zeros_2】 shape = {m_zeros_2.shape}")
print(f"【m_zeros_2】 =\n{m_zeros_2}")
print()

【m_ones】 shape = (2, 2)
【m_ones】 =
[[1. 1.]
 [1. 1.]]

【m_zeros】 shape = (3, 3)
【m_zeros】 =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

【m_zeros_1】 shape = (2, 2)
【m_zeros_1】 =
[[0. 0.]
 [0. 0.]]

【m_zeros_2】 shape = (3, 2)
【m_zeros_2】 =
[[5 5]
 [5 5]
 [5 5]]



In [5]:
# 特殊矩阵
# 单位矩阵
m_eye = tf.eye(3, 3)

# 对角阵
m_diag = tf.linalg.diag([1, 2, 3])

print(f"【m_eye】 shape = {m_eye.shape}")
print(f"【m_eye】 =\n{m_eye}")
print()
print(f"【m_diag】 shape = {m_diag.shape}")
print(f"【m_diag】 =\n{m_diag}")
print()

【m_eye】 shape = (3, 3)
【m_eye】 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

【m_diag】 shape = (3, 3)
【m_diag】 =
[[1 0 0]
 [0 2 0]
 [0 0 3]]



In [6]:
# 初始化 随机张量

#均匀分布随机
tf.random.set_seed(1.0)
vec_a = tf.random.uniform([5], minval=0, maxval=10)

#正态分布随机
m_b = tf.random.normal([3, 3], mean=0.0, stddev=1.0)

#正态分布随机，剔除2倍方差以外数据重新生成
m_c = tf.random.truncated_normal((4, 4), mean=0.0, stddev=1.0, dtype=tf.float32)


print(f"【vec_a】 shape = {vec_a.shape}")
print(f"【vec_a】 =\n{vec_a}")
print()
print(f"【m_b】 shape = {m_b.shape}")
print(f"【m_b】 =\n{m_b}")
print()
print(f"【m_c】 shape = {m_c.shape}")
print(f"【m_c】 =\n{m_c}")
print()

【vec_a】 shape = (5,)
【vec_a】 =
[1.6513085 9.014812  6.309742  4.345461  2.9193902]

【m_b】 shape = (3, 3)
【m_b】 =
[[ 0.40308788 -1.0880208  -0.06309535]
 [ 1.3365567   0.7117601  -0.48928645]
 [-0.7642213  -1.0372486  -1.2519338 ]]

【m_c】 shape = (4, 4)
【m_c】 =
[[-0.45701224 -0.40686727  0.72857773 -0.8929778 ]
 [-0.36940458  0.32348856  1.1938332   0.88829905]
 [ 1.259856   -1.9595189  -0.2022444   0.2944969 ]
 [-0.46872804  1.294942    1.4814218   0.08109535]]



In [7]:
# 通过设置seed，使得不同时间获得相同的随机值
tf.random.set_seed(1.0)
vec_a = tf.random.uniform([5], minval=0, maxval=10)

tf.random.set_seed(10)
vec_b = tf.random.uniform([5], minval=0, maxval=10)

tf.random.set_seed(1.0)
vec_c = tf.random.uniform([5], minval=0, maxval=10)

print(f"【vec_a】 shape = {vec_a.shape}")
print(f"【vec_a】 =\n{vec_a}")
print()
print(f"【vec_b】 shape = {vec_b.shape}")
print(f"【vec_b】 =\n{vec_b}")
print()
print(f"【vec_c】 shape = {vec_c.shape}")
print(f"【vec_c】 =\n{vec_c}")
print()

【vec_a】 shape = (5,)
【vec_a】 =
[1.6513085 9.014812  6.309742  4.345461  2.9193902]

【vec_b】 shape = (5,)
【vec_b】 =
[6.4415097 8.082472  8.976547  6.3689017 6.270969 ]

【vec_c】 shape = (5,)
【vec_c】 =
[1.6513085 9.014812  6.309742  4.345461  2.9193902]



### 数据索引 / 切片

In [8]:
tf.random.set_seed(3)
mtx_a = tf.random.uniform([5, 5], minval=0, maxval=10, dtype=tf.int32)

mtx_a

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[4, 7, 4, 2, 9],
       [9, 1, 2, 4, 7],
       [7, 2, 7, 4, 0],
       [9, 6, 9, 7, 2],
       [3, 7, 0, 0, 3]], dtype=int32)>

In [9]:
# 默认从第一个轴，进行 索引 / 切片

# 取 第1行 数据
print(mtx_a[0])
print()

# 取 最后1行 数据
print(mtx_a[-1])
print()

# 取 第2行、第3列 数据
print(mtx_a[1][3])
print(mtx_a[1, 3])
print()

tf.Tensor([4 7 4 2 9], shape=(5,), dtype=int32)

tf.Tensor([3 7 0 0 3], shape=(5,), dtype=int32)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)



In [10]:
# 取 第1-3行 的切片数据
tf.print(mtx_a[1:4, :])
print()
tf.print(tf.slice(mtx_a, [1, 0], [3, 5])) # tf.slice(input, begin_vector, size_vector)
print()

#第1行至最后1行，第0列到最后1列，每隔1列取1列
tf.print(mtx_a[1:, ::2])

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]

[[9 2 7]
 [7 7 0]
 [9 9 2]
 [3 0 3]]


In [11]:
#对变量来说，还可以使用索引和切片修改部分元素
x = tf.Variable([[1, 2], [3, 4]], dtype=tf.float32)

print(f"【x】 shape = {x.shape}")
print(f"【x】 =\n{x}")
print()
x[1, :].assign(tf.constant([0.0, 0.0]))
print(f"【x】 shape = {x.shape}")
print(f"【x】 =\n{x}")
print()

【x】 shape = (2, 2)
【x】 =
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

【x】 shape = (2, 2)
【x】 =
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [0., 0.]], dtype=float32)>



In [12]:
a = tf.random.uniform([3, 3, 3], minval=0, maxval=10, dtype=tf.int32)

print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

【a】 shape = (3, 3, 3)
【a】 =
[[[7 3 9]
  [9 0 7]
  [9 6 7]]

 [[1 3 3]
  [0 8 1]
  [3 1 0]]

 [[4 0 6]
  [6 2 2]
  [7 9 5]]]



In [13]:
#省略号可以表示多个冒号
tf.print(a[:, :, 1])

[[3 0 6]
 [3 8 1]
 [0 2 9]]


In [14]:
# 对于不规则的切片提取, 可以使用 tf.gather, tf.gather_nd, tf.boolean_mask

# 3个班级，每个班级有 5个学生，每个学生有 3门功课的成绩
scores = tf.random.uniform((3, 5, 3), minval=0, maxval=100, dtype=tf.int32)
tf.print(scores)

[[[52 82 66]
  [55 17 86]
  [14 8 36]
  [94 16 13]
  [78 41 77]]

 [[53 51 93]
  [22 91 56]
  [73 31 18]
  [9 93 87]
  [21 25 40]]

 [[16 76 32]
  [49 88 24]
  [80 70 46]
  [72 63 96]
  [16 44 31]]]


In [15]:
# 抽取每个班级第0个学生，第2个学生，第4个学生的全部成绩
p = tf.gather(scores, [0, 2, 4], axis=1)

tf.print(p)

[[[52 82 66]
  [14 8 36]
  [78 41 77]]

 [[53 51 93]
  [73 31 18]
  [21 25 40]]

 [[16 76 32]
  [80 70 46]
  [16 44 31]]]


In [16]:
# 抽取第0个班级第0个学生，第1个班级的第2个学生，第2个班级的第4个学生的全部成绩

#indices的长度为采样样本的个数，每个元素为采样位置的坐标
s = tf.gather_nd(scores, indices=[(0, 0), (1, 2), (2, 4)])
s

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[52, 82, 66],
       [73, 31, 18],
       [16, 44, 31]], dtype=int32)>

In [17]:
#抽取每个班级第1个学生，第2个学生，第3个学生的全部成绩
p = tf.boolean_mask(scores, [False, True, True, True, False], axis=1)
tf.print(p)

[[[55 17 86]
  [14 8 36]
  [94 16 13]]

 [[22 91 56]
  [73 31 18]
  [9 93 87]]

 [[49 88 24]
  [80 70 46]
  [72 63 96]]]


In [18]:
#利用tf.boolean_mask可以实现布尔索引

#找到矩阵中小于0的元素
c = tf.constant([[-1, 1, -1], [2, 2, -2], [3, -3, 3]], dtype=tf.float32)
tf.print(c, "\n")

tf.print(tf.boolean_mask(c, c<0), "\n")
print()
tf.print(c[c<0]) #布尔索引，为boolean_mask的语法糖形式

[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]] 

[-1 -1 -2 -3] 


[-1 -1 -2 -3]


In [19]:
#找到张量中小于0的元素, 将其换成np.nan得到新的张量
#tf.where和np.where作用类似，可以理解为if的张量版本

c = tf.constant([[-1, 1, -1], [2, 2, -2], [3, -3, 3]], dtype=tf.float32)

print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

#如果where只有一个参数，将返回所有满足条件的位置坐标
indices = tf.where(c < 0)

print(f"【indices】 shape = {indices.shape}")
print(f"【indices】 =\n{indices}")
print()

b = tf.fill(c.shape, 0.0)
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

a = tf.where(c<0, b, c)
print(f"【a】 shape = {a.shape}")
# print(f"【a】 =\n{a}")
print()
a

【c】 shape = (3, 3)
【c】 =
[[-1.  1. -1.]
 [ 2.  2. -2.]
 [ 3. -3.  3.]]

【indices】 shape = (4, 2)
【indices】 =
[[0 0]
 [0 2]
 [1 2]
 [2 1]]

【b】 shape = (3, 3)
【b】 =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

【a】 shape = (3, 3)



<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [2., 2., 0.],
       [3., 0., 3.]], dtype=float32)>

In [20]:
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3., -3.,  3.]], dtype=float32)>

In [21]:
cc = tf.scatter_nd([[0, 0], [2, 1]], [c[0, 0], c[2, 1]], c.shape)
cc

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0., -3.,  0.]], dtype=float32)>

In [22]:
#将张量的第[0, 0]和[2, 1]两个位置元素替换为0, 得到新的张量
d = c - cc
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3.,  0.,  3.]], dtype=float32)>

In [23]:
#scatter_nd的作用和gather_nd有些相反
#可以将某些值插入到一个给定shape的全0的张量的指定位置处。

indices = tf.where(c < 0)

print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()
print(f"【indices】 shape = {indices.shape}")
print(f"【indices】 =\n{indices}")
print()

n = tf.gather_nd(c, indices)
print(f"【n】 shape = {n.shape}")
print(f"【n】 =\n{n}")
print()

tf.scatter_nd(indices, n, c.shape)

【c】 shape = (3, 3)
【c】 =
[[-1.  1. -1.]
 [ 2.  2. -2.]
 [ 3. -3.  3.]]

【indices】 shape = (4, 2)
【indices】 =
[[0 0]
 [0 2]
 [1 2]
 [2 1]]

【n】 shape = (4,)
【n】 =
[-1. -1. -2. -3.]



<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

### 维度转换

- **tf.reshape** 可以改变张量的形状。

- **tf.squeeze** 可以减少维度。

- **tf.expand_dims** 可以增加维度。

- **tf.transpose** 可以交换维度。

In [24]:
a = tf.random.uniform(shape=[1, 2, 3, 4], minval=0, maxval=255, dtype=tf.int32)
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

【a】 shape = (1, 2, 3, 4)
【a】 =
[[[[100  44 181  14]
   [ 90  53 205 141]
   [ 14  24 239  46]]

  [[225 174 212  78]
   [ 14 144 209 106]
   [165  41  44  38]]]]



In [25]:
# 使用reshape，改变张量形状为 (4,6): 不会改变张量元素的存储顺序
b = tf.reshape(a, [4, 6])
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

# 改回成 [1,3,3,2] 形状的张量
c = tf.reshape(b, [1, 2, 3, 4])
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【b】 shape = (4, 6)
【b】 =
[[100  44 181  14  90  53]
 [205 141  14  24 239  46]
 [225 174 212  78  14 144]
 [209 106 165  41  44  38]]

【c】 shape = (1, 2, 3, 4)
【c】 =
[[[[100  44 181  14]
   [ 90  53 205 141]
   [ 14  24 239  46]]

  [[225 174 212  78]
   [ 14 144 209 106]
   [165  41  44  38]]]]



In [26]:
# 如果张量在某个维度上只有一个元素，利用tf.squeeze可以消除这个维度
s = tf.squeeze(a)
print(f"【s】 shape = {s.shape}")
print(f"【s】 =\n{s}")
print()

# 在第0维插入长度为1的一个维度
d = tf.expand_dims(s, axis=0)
print(f"【d】 shape = {d.shape}")
print(f"【d】 =\n{d}")
print()

【s】 shape = (2, 3, 4)
【s】 =
[[[100  44 181  14]
  [ 90  53 205 141]
  [ 14  24 239  46]]

 [[225 174 212  78]
  [ 14 144 209 106]
  [165  41  44  38]]]

【d】 shape = (1, 2, 3, 4)
【d】 =
[[[[100  44 181  14]
   [ 90  53 205 141]
   [ 14  24 239  46]]

  [[225 174 212  78]
   [ 14 144 209 106]
   [165  41  44  38]]]]



In [27]:
# Batch, Height, Width, Channel
a = tf.random.uniform(shape=[100, 600, 600, 4], minval=0, maxval=255, dtype=tf.int32)
print(f"【a】 shape = {a.shape}")
# print(f"【a】 =\n{a}")
print()

# 转换成 Channel, Height, Width, Batch
s = tf.transpose(a, perm=[3, 1, 2, 0])
print(f"【s】 shape = {s.shape}")
# print(f"【s】 =\n{s}")
print()

【a】 shape = (100, 600, 600, 4)

【s】 shape = (4, 600, 600, 100)



### 张量合并 / 分割

#### 合并张量

- **tf.concat**: 拼接张量，不增加张量维度；
- **tf.stack**: 堆叠张量，会增加张量维度；

In [28]:
# 张量拼接: tf.concat
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.constant([[5.0, 6.0], [7.0, 8.0]])
c = tf.constant([[9.0, 10.0], [11.0, 12.0]])
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

v = tf.concat([a, b, c], axis=0)
h = tf.concat([a, b, c], axis=1)

print(f"【v】 shape = {v.shape}")
print(f"【v】 =\n{v}")
print()
print(f"【h】 shape = {h.shape}")
print(f"【h】 =\n{h}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

【b】 shape = (2, 2)
【b】 =
[[5. 6.]
 [7. 8.]]

【c】 shape = (2, 2)
【c】 =
[[ 9. 10.]
 [11. 12.]]

【v】 shape = (6, 2)
【v】 =
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]

【h】 shape = (2, 6)
【h】 =
[[ 1.  2.  5.  6.  9. 10.]
 [ 3.  4.  7.  8. 11. 12.]]



In [29]:
# 张量堆叠: tf.stack
v = tf.stack([a, b, c])
h = tf.stack([a, b, c], axis=1)

print(f"【v】 shape = {v.shape}")
print(f"【v】 =\n{v}")
print()
print(f"【h】 shape = {h.shape}")
print(f"【h】 =\n{h}")
print()

【v】 shape = (3, 2, 2)
【v】 =
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]

【h】 shape = (2, 3, 2)
【h】 =
[[[ 1.  2.]
  [ 5.  6.]
  [ 9. 10.]]

 [[ 3.  4.]
  [ 7.  8.]
  [11. 12.]]]



#### 分割张量

In [30]:
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.constant([[5.0, 6.0], [7.0, 8.0]])
c = tf.constant([[9.0, 10.0], [11.0, 12.0]])

c = tf.concat([a, b, c], axis=0)
c

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [31]:
#tf.split(value,num_or_size_splits,axis)
# 平均分割: 指定分割份数
l = tf.split(c, 3, axis=0)
for item in l:
    print(item)
    print()

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[ 9. 10.]
 [11. 12.]], shape=(2, 2), dtype=float32)



In [32]:
# 指定分割: 指定每份张量的 元素个数
l = tf.split(c, [1, 2, 3], axis=0) #指定每份的记录数量
for item in l:
    print(item)
    print()




tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)

tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(3, 2), dtype=float32)

