# 张量(Tensor)的数学运算

In [1]:
import os

import tensorflow as tf
import numpy as np

os.environ["CUDA_VISIBLE_DEVICES"] = "3"
tf.__version__

'2.1.0'

张量数学运算主要有：
- **标量运算**
- **向量运算**
- **矩阵运算**
- **张量运算的广播机制**

### 标量运算

加、减、乘、除、乘方，以及三角函数，指数，对数等常见函数，逻辑比较运算符等都是标量运算；

【标量运算符】的特点是 **对张量实施逐元素运算**；

In [2]:
a = tf.constant([[1.0, 2], [-3, 4.0]])
b = tf.constant([[5.0, 6], [7.0, 8.0]])
# print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()
# print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

# 加法
print("【加法】：")
c = a + b  #运算符重载
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

# 减法
print("【减法】：")
c = a - b  #运算符重载
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【a】 =
[[ 1.  2.]
 [-3.  4.]]

【b】 =
[[5. 6.]
 [7. 8.]]

【加法】：
【c】 =
[[ 6.  8.]
 [ 4. 12.]]

【减法】：
【c】 =
[[ -4.  -4.]
 [-10.  -4.]]



In [3]:
# print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()
# print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

# 乘法
print("【乘法】：")
c = a * b  #运算符重载
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

# 除法
print("【除法】：")
c = a / b  #运算符重载
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【a】 =
[[ 1.  2.]
 [-3.  4.]]

【b】 =
[[5. 6.]
 [7. 8.]]

【乘法】：
【c】 =
[[  5.  12.]
 [-21.  32.]]

【除法】：
【c】 =
[[ 0.2         0.33333334]
 [-0.42857143  0.5       ]]



In [4]:
# print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()
# print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

# 地板除
print("【地板除】：")
c = a // 2
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

# 模运算%
print("【模运算】：")
c = a % 3
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【a】 =
[[ 1.  2.]
 [-3.  4.]]

【b】 =
[[5. 6.]
 [7. 8.]]

【地板除】：
【c】 =
[[ 0.  1.]
 [-2.  2.]]

【模运算】：
【c】 =
[[ 1.  2.]
 [-0.  1.]]



In [5]:
# print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

c = a ** 2
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

c = a ** (0.5)
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

c = tf.sqrt(a)
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【a】 =
[[ 1.  2.]
 [-3.  4.]]

【c】 =
[[ 1.  4.]
 [ 9. 16.]]

【c】 =
[[1.        1.4142135]
 [      nan 2.       ]]

【c】 =
[[1.        1.4142135]
 [      nan 2.       ]]



In [6]:
# 逻辑运算

# print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

c = (a > 2)
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

c = (a >= 2) & (a <= 4)
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

c = (a >= 2) | (a <= 3)
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

c = (a == 2)
# print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【a】 =
[[ 1.  2.]
 [-3.  4.]]

【c】 =
[[False False]
 [False  True]]

【c】 =
[[False  True]
 [False  True]]

【c】 =
[[ True  True]
 [ True  True]]

【c】 =
[[False  True]
 [False False]]



In [7]:
# 其他
a = tf.constant([1.0, 8.0])
b = tf.constant([5.0, 6.0])
c = tf.constant([6.0, 7.0])
tf.add_n([a, b, c])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 21.], dtype=float32)>

In [8]:
tf.maximum(a, b)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 8.], dtype=float32)>

In [9]:
tf.minimum(a, b)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 6.], dtype=float32)>

### 向量运算

In [10]:
#向量reduce
a = tf.range(1, 10)
tf.print(a.shape)
tf.print(f"sum={tf.reduce_sum(a)}")
tf.print(f"mean={tf.reduce_mean(a)}")
tf.print(f"max={tf.reduce_max(a)}")
tf.print(f"min={tf.reduce_min(a)}")
tf.print(f"逐元素连乘={tf.reduce_prod(a)}")

TensorShape([9])
sum=45
mean=5
max=9
min=1
逐元素连乘=362880


In [11]:
#张量指定维度进行reduce
b = tf.reshape(a, (3, 3))
tf.print(b)
print()
tf.print(tf.reduce_sum(b, axis=1, keepdims=True))
print()
tf.print(tf.reduce_sum(b, axis=0, keepdims=True))
print()
tf.print(tf.reduce_sum(b, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[6]
 [15]
 [24]]

[[12 15 18]]

[12 15 18]


In [12]:
#bool类型的reduce
p = tf.constant([True, False, False])
q = tf.constant([False, True, False])

tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

0
1


In [13]:
#利用tf.foldr实现tf.reduce_sum

s = tf.foldr(lambda a, b: a + b, a)
tf.print(s)

45


In [14]:
#cum扫描累积, 逐元素 累加 / 累乘
a = tf.range(1, 10)
tf.print(a)
tf.print(tf.math.cumsum(a))
tf.print(tf.math.cumprod(a))

[1 2 3 ... 7 8 9]
[1 3 6 ... 28 36 45]
[1 2 6 ... 5040 40320 362880]


In [15]:
#arg 最大 / 最小值 所在位置的索引
a = tf.range(1, 10)
tf.print(a)
tf.print(tf.argmax(a))
tf.print(tf.argmin(a))
print()

a = tf.random.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)
tf.print(a)
print()
tf.print(f"max val index={tf.argmax(a)}")
tf.print(f"min val index={tf.argmin(a)}")
print()
tf.print(f"max val index={tf.argmax(a, axis=1)}")
tf.print(f"min val index={tf.argmin(a, axis=1)}")

[1 2 3 ... 7 8 9]
8
0

[[1 3 8]
 [8 0 3]
 [2 7 4]]

max val index=[1 2 0]
min val index=[0 1 1]

max val index=[2 0 1]
min val index=[0 1 0]


In [16]:
#tf.math.top_k可以用于对张量排序
a = tf.constant([1, 3, 7, 5, 4, 8])

values, indices = tf.math.top_k(a, 3, sorted=True)
tf.print(f"top k val = {values}")
tf.print(f"top k val index = {indices}")

#利用tf.math.top_k可以在TensorFlow中实现KNN算法

top k val = [8 7 5]
top k val index = [5 2 3]


### 矩阵运算

矩阵运算包括：
- 矩阵乘法
- 矩阵转置
- 矩阵求逆
- 矩阵求迹
- 矩阵范数
- 矩阵行列式
- 矩阵求特征值
- 矩阵分解
- ...

除了一些常用的运算外，大部分和矩阵有关的运算都在 **tf.linalg子包** 中。

In [17]:
#矩阵乘法
a = tf.constant([[1, 3], [5, 7]])
b = tf.constant([[2, 4], [6, 8]])
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

c = tf.matmul(a, b)
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

c = a@b  #等价于tf.matmul(a,b)
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

【a】 shape = (2, 2)
【a】 =
[[1 3]
 [5 7]]

【b】 shape = (2, 2)
【b】 =
[[2 4]
 [6 8]]

【c】 shape = (2, 2)
【c】 =
[[20 28]
 [52 76]]

【c】 shape = (2, 2)
【c】 =
[[20 28]
 [52 76]]



In [18]:
#矩阵转置
c = tf.transpose(c)
print("矩阵的zhuanzhi:")
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

矩阵的zhuanzhi:
【c】 shape = (2, 2)
【c】 =
[[20 52]
 [28 76]]



In [19]:
#矩阵求逆，必须为tf.float32或tf.double类型
a = tf.constant([[1.0,  2], [3.0, 4]], dtype = tf.float32)
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

b = tf.linalg.inv(a)
print("矩阵求逆:")
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求逆:
【b】 shape = (2, 2)
【b】 =
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]



In [20]:
#矩阵求迹(trace)
a = tf.constant([[1.0, 2], [3, 4]])
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

b = tf.linalg.trace(a)
print("矩阵求迹:")
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求迹:
【b】 shape = ()
【b】 =
5.0



In [21]:
#矩阵求范数
a = tf.constant([[1.0, 2], [3, 4]])
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

b = tf.linalg.norm(a)
print("矩阵求范数:")
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求范数:
【b】 shape = ()
【b】 =
5.4772257804870605



In [22]:
#矩阵求行列式
a = tf.constant([[1.0, 2], [3, 4]])
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

b = tf.linalg.det(a)
print("矩阵求行列式:")
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求行列式:
【b】 shape = ()
【b】 =
-2.0



In [23]:
#矩阵求特征值
a = tf.constant([[1.0, 2], [3, 4]], dtype=tf.float32)
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

b = tf.linalg.eigvalsh(a)
print("矩阵求特征值:")
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求特征值:
【b】 shape = (2,)
【b】 =
[-0.8541021  5.854102 ]



In [24]:
#矩阵求qr分解
a = tf.constant([[1.0, 2], [3, 4]], dtype=tf.float32)
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

b, c = tf.linalg.qr(a)
print("矩阵求qr分解:")
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

d = b @ c
print(f"【b@c】 shape = {d.shape}")
print(f"【b@c】 =\n{d}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求qr分解:
【b】 shape = (2, 2)
【b】 =
[[-0.3162278  -0.9486833 ]
 [-0.9486833   0.31622773]]

【c】 shape = (2, 2)
【c】 =
[[-3.1622777  -4.4271884 ]
 [ 0.         -0.63245535]]

【b@c】 shape = (2, 2)
【b@c】 =
[[1.0000001 1.9999998]
 [3.        4.       ]]



In [25]:
#矩阵求SVD分解
a = tf.constant([[1.0, 2], [3, 4]], dtype=tf.float32)
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()

v, s, d = tf.linalg.svd(a)
print("矩阵求SVD分解:")
print(f"【v】 shape = {v.shape}")
print(f"【v】 =\n{v}")
print()
print(f"【s】 shape = {s.shape}")
print(f"【s】 =\n{s}")
print()
print(f"【d】 shape = {d.shape}")
print(f"【d】 =\n{d}")
print()

e = tf.matmul(tf.matmul(s, tf.linalg.diag(v)), d)
print(f"【e】 shape = {e.shape}")
print(f"【e】 =\n{e}")
print()
e = s @ tf.linalg.diag(v) @ d
print(f"【e】 shape = {e.shape}")
print(f"【e】 =\n{e}")
print()

【a】 shape = (2, 2)
【a】 =
[[1. 2.]
 [3. 4.]]

矩阵求SVD分解:
【v】 shape = (2,)
【v】 =
[5.4649854  0.36596614]

【s】 shape = (2, 2)
【s】 =
[[ 0.4045535 -0.9145143]
 [ 0.9145143  0.4045535]]

【d】 shape = (2, 2)
【d】 =
[[ 0.5760484  0.8174156]
 [ 0.8174156 -0.5760484]]

【e】 shape = (2, 2)
【e】 =
[[0.9999996 1.9999996]
 [2.9999998 4.       ]]

【e】 shape = (2, 2)
【e】 =
[[0.9999996 1.9999996]
 [2.9999998 4.       ]]



### 广播机制

TensorFlow的广播规则和numpy是一样的:

1. 若两个张量的维度长度不同，需将维度较小的张量扩展至较大张量的维度长度；
2. 若两个张量在某个维度上的长度是相同的，或其中一个张量在该维度上的长度为1，则称两个张量在该维度上是相容的；
3. 若两个张量在所有维度上都是相容的，它们就能使用广播机制；
4. 将某维度长度较小的张量扩充至较大维度长度，即对维度长度较小的张量，在该维度方向进行复制，只到维度长度一致；
5. 广播之后，每个维度的长度将取两个张量在该维度长度的较大值；


In [26]:
a = tf.constant([1, 2, 3])
b = tf.constant([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
c = tf.broadcast_to(a, b.shape)
print(f"【a】 shape = {a.shape}")
print(f"【a】 =\n{a}")
print()
print(f"【b】 shape = {b.shape}")
print(f"【b】 =\n{b}")
print()
print(f"【c】 shape = {c.shape}")
print(f"【c】 =\n{c}")
print()

d = a + b # 等价于 b + tf.broadcast_to(a,b.shape)
print(f"【d】 shape = {d.shape}")
print(f"【d】 =\n{d}")
print()

d = b + c
print(f"【d】 shape = {d.shape}")
print(f"【d】 =\n{d}")
print()

【a】 shape = (3,)
【a】 =
[1 2 3]

【b】 shape = (3, 3)
【b】 =
[[0 0 0]
 [1 1 1]
 [2 2 2]]

【c】 shape = (3, 3)
【c】 =
[[1 2 3]
 [1 2 3]
 [1 2 3]]

【d】 shape = (3, 3)
【d】 =
[[1 2 3]
 [2 3 4]
 [3 4 5]]

【d】 shape = (3, 3)
【d】 =
[[1 2 3]
 [2 3 4]
 [3 4 5]]



In [27]:
#计算广播后计算结果的形状，静态形状，TensorShape类型参数
tf.broadcast_static_shape(a.shape, b.shape)

TensorShape([3, 3])

In [28]:
#计算广播后计算结果的形状，动态形状，Tensor类型参数
c = tf.constant([1, 2, 3])
d = tf.constant([[1], [2], [3]])
tf.broadcast_dynamic_shape(tf.shape(c), tf.shape(d))




<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>