# TensorFlow张量数据

In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.1.0


## 数据类型

### 常量

In [2]:
# 常量值不可以改变，常量的重新赋值相当于创造新的内存空间
c = tf.constant([1.0,2.0])
print(c)
print(f"id={id(c)}")
print()
c = c + tf.constant([1.0,1.0])
print(c)
print(f"id={id(c)}")

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
id=140488032128528

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
id=140488031690832


### 变量

In [3]:
# 变量的值可以改变，可以通过assign, assign_add等方法给变量重新赋值
v = tf.Variable([1.0, 2.0], name = "vv")
print(v)
print(f"id={id(v)}")
print()
v.assign_add([1.0,1.0])
print(v)
print(f"id={id(v)}")

<tf.Variable 'vv:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
id=140488031728208

<tf.Variable 'vv:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
id=140488031728208


## 张量结构

In [4]:
i = tf.constant(1) # tf.int32 类型常量
l = tf.constant(1, dtype = tf.int64) # tf.int64 类型常量
f = tf.constant(1.23) #tf.float32 类型常量
d = tf.constant(3.14, dtype = tf.double) # tf.double 类型常量
s = tf.constant("hello world") # tf.string类型常量
b = tf.constant(True) #tf.bool类型常量


print(tf.int64 == np.int64) 
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode) # tf.string类型和np.unicode类型不等价

i, l, f, d, s, b

True
True
True
False


(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.23>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3.14>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

In [5]:
# 标量，0维张量
scalar = tf.constant(True)

print(f"【scalar rank】: {tf.rank(scalar)}")
print(f"【scalar rank】: {scalar.numpy().ndim}")  # tf.rank的作用和numpy的ndim方法相同
print(scalar)
print()

# 向量，1维张量
vector = tf.constant([1.0,2.0,3.0,4.0])

print(f"【vector rank】: {tf.rank(vector)}")
print(vector)
print()

# 矩阵, 2维张量
matrix = tf.constant([[1.0,2.0],[3.0,4.0]]) 

print(f"【matrix rank】: {tf.rank(matrix)}")
print(matrix)
print()

# 3维张量
tensor3 = tf.constant([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])

print(f"【tensor rank】: {tf.rank(tensor3)}")
print(tensor3)
print()

【scalar rank】: 0
【scalar rank】: 0
tf.Tensor(True, shape=(), dtype=bool)

【vector rank】: 1
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)

【matrix rank】: 2
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

【tensor rank】: 3
tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)



In [6]:
# 使用tf.cast 修改张量的元素数据类型
h = tf.constant([123, 456], dtype=tf.int32)
f = tf.cast(h, tf.float32)
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>
